# Kubernetes Deployment manifest for Elasticsearch
# This deployment manages a single-node Elasticsearch instance for log aggregation
# and search functionality.
#
# Key components:
# - Uses official Elasticsearch 8.5.0 image
# - Runs in logging namespace
# - Configured with resource limits and requests
# - Single-node discovery for development use
# - Disabled security features for simplicity
# - Exposes port 9200 for REST API
#
# References:
# - Elasticsearch docs: https://www.elastic.co/guide/en/elasticsearch/reference/8.5/docker.html
# - Kubernetes Deployment API: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "512Mi"
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 9200
