# Kubernetes Service manifest for Prometheus
# This service exposes the Prometheus deployment within the cluster
# to enable metrics collection and monitoring.
#
# Key components:
# - ClusterIP service type (default) for internal cluster access
# - Exposes port 9090 for Prometheus web UI and API
# - Selects pods with app=prometheus label
# - Runs in monitoring namespace
#
# References:
# - Kubernetes Service API: https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
# - Prometheus docs: https://prometheus.io/docs/prometheus/latest/getting_started/
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
