apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ecommerce
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64_encoded_credentials>
---
apiVersion: v1
kind: Secret
metadata:
  name: service-secrets
  namespace: ecommerce
type: Opaque
data:
  rabbitmq-username: YWRtaW4=
  rabbitmq-password: YWRtaW5wYXNzd29yZA==
  postgres-username: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXNwYXNz
