# Kubernetes IstioOperator manifest for Istio Service Mesh
# This manifest configures the core Istio installation and components.
#
# Key components:
# - Uses demo profile for development environments
# - Enables automatic mTLS between services
# - Configures DNS capture and protocol detection
# - Sets resource limits and security contexts
# - Enables ingress gateway
#
# References:
# - Istio Installation: https://istio.io/latest/docs/setup/install/istioctl/
# - IstioOperator API: https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/
# - Security Best Practices: https://istio.io/latest/docs/ops/best-practices/security/

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: demo
  meshConfig:
    enableAutoMtls: true
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_PROTOCOL_DETECT: "true"
    pilot:
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          fsGroup: 1337
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          securityContext:
            fsGroup: 1337
            runAsGroup: 1337
            runAsNonRoot: true
            runAsUser: 1337
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        privileged: false
        enableCoreDump: false
      proxy_init:
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
