apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: default-mesh-config
  namespace: istio-system
spec:
  host: "*.local"
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        tcpKeepalive:
          time: 7200s
          interval: 75s
          probes: 9
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
