# Istio Gateway and VirtualService configuration for the E-commerce Application
# This configuration sets up the ingress gateway and routing rules for the microservices.
#
# Key components:
# - Gateway configuration:
#   * Uses Istio ingress gateway
#   * Exposes HTTP port 80
#   * Handles traffic for ecommerce.local domain
# - VirtualService configuration:
#   * Routes traffic based on URI prefixes to different microservices
#   * Manages traffic for catalog, search and order services
#   * Uses FQDN format for service routing
#
# References:
# - Istio Gateway: https://istio.io/latest/docs/reference/config/networking/gateway/
# - Istio VirtualService: https://istio.io/latest/docs/reference/config/networking/virtual-service/
# - Traffic Management: https://istio.io/latest/docs/concepts/traffic-management/

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ecommerce-gateway
  namespace: ecommerce
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "ecommerce.local"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ecommerce-vs
  namespace: ecommerce
spec:
  hosts:
    - "ecommerce.local"
  gateways:
    - ecommerce-gateway
  http:
    - match:
        - uri:
            prefix: /catalog
      route:
        - destination:
            host: catalog-service.ecommerce.svc.cluster.local
            port:
              number: 5001
    - match:
        - uri:
            prefix: /search
      route:
        - destination:
            host: search-service.ecommerce.svc.cluster.local
            port:
              number: 5002
    - match:
        - uri:
            prefix: /order
      route:
        - destination:
            host: order-service.ecommerce.svc.cluster.local
            port:
              number: 5003
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend-service.ecommerce.svc.cluster.local
            port:
              number: 5004
