apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: egitangu/frontend-service:latest
        ports:
        - containerPort: 8004
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "200m"
            memory: "64Mi"
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
