apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: egitangu/frontend-service:latest
          ports:
            - containerPort: 5004
          readinessProbe:
            httpGet:
              path: /health
              port: 5004
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5004
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "200m"
              memory: "64Mi"
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
      volumes:
        - name: logs-and-metrics
          emptyDir: {}
