# Kubernetes Deployment manifest for RabbitMQ
# This deployment manages a RabbitMQ message broker instance for asynchronous communication.
#
# Key components:
# - Uses official RabbitMQ image with management plugin
# - Runs in messaging namespace
# - Exposes AMQP (5672) and management (15672) ports
# - Configured with resource limits and health checks
#
# References:
# - RabbitMQ Docker: https://hub.docker.com/_/rabbitmq
# - Kubernetes Deployment API: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
# - RabbitMQ Monitoring: https://www.rabbitmq.com/monitoring.html
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: messaging
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 30
            periodSeconds: 20
