# Service manifest for RabbitMQ
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: messaging
spec:
  ports:
  - port: 5672
    targetPort: 5672
  - port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
