# Kubernetes Deployment manifest for the Search Service
# This deployment manages the search service which provides product search functionality
# using Elasticsearch as the search engine.
#
# Key components:
# - Uses egitangu/search-service:latest image
# - Runs in ecommerce namespace
# - Configured with resource limits and requests
# - Connects to Elasticsearch, PostgreSQL and RabbitMQ services
# - Includes readiness/liveness probes for health monitoring
# - Mounts volume for logs and metrics
#
# References:
# - Kubernetes Deployment API: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
# - Kubernetes Probes: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: ecommerce
  labels:
    app: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: search-service
          image: egitangu/search-service:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 5002
          env:
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch.logging.svc.cluster.local"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: POSTGRES_HOST
              value: "postgres-postgresql.database.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: postgres-database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: postgres-password
            - name: RABBITMQ_HOST
              value: "rabbitmq.messaging.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: rabbitmq-password
          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: logs-and-metrics
              mountPath: /app/logs
      volumes:
        - name: logs-and-metrics
          emptyDir: {}
