apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: ecommerce
  labels:
    app: search-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: egitangu/search-service:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5002
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: rabbitmq-password
          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: logs-and-metrics
          emptyDir: {}
