apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: ecommerce
  labels:
    app: search-service
spec:
  type: ClusterIP
  ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
  selector:
    app: search-service
