kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: worker
  - role: control-plane
    image: kindest/node:v1.28.0
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
            authorization-mode: "AlwaysAllow"
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            "enable-admission-plugins": "NodeRestriction"
        controllerManager:
          extraArgs:
            "terminated-pod-gc-threshold": "100"
        scheduler:
          extraArgs:
            "v": "2"
