# Kubernetes StorageClass manifest for local path provisioner
# This StorageClass configures the default storage provisioning behavior
# for persistent volumes in the cluster.
#
# Key components:
# - Uses Rancher's local-path provisioner for development environments
# - Set as default StorageClass via annotation
# - WaitForFirstConsumer binding mode for better pod scheduling
# - Delete reclaim policy to clean up volumes automatically
#
# References:
# - StorageClass API: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/storage-class-v1/
# - Local Path Provisioner: https://github.com/rancher/local-path-provisioner
# - Storage Classes: https://kubernetes.io/docs/concepts/storage/storage-classes/

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
