apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: ecommerce
  labels:
    app: catalog-service
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
  selector:
    app: catalog-service
