# Kubernetes Service manifest for the Catalog Service
# This service exposes the catalog service deployment within the cluster
# to enable product catalog functionality.
#
# Key components:
# - ClusterIP service type for internal cluster access
# - Exposes port 5001 for the catalog service
# - Selects pods with app=catalog-service label
# - Runs in ecommerce namespace
#
# References:
# - Kubernetes Service API: https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
# - Service Types: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: ecommerce
  labels:
    app: catalog-service
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
  selector:
    app: catalog-service
