# Kubernetes Deployment manifest for the Order Service
# This deployment manages the order service which handles customer order processing
# and management.
#
# Key components:
# - Uses egitangu/order-service:latest image
# - Runs in ecommerce namespace
# - Configured with resource limits and requests
# - Includes readiness/liveness probes for health monitoring
# - Uses imagePullSecrets for private registry access
#
# References:
# - Kubernetes Deployment API: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
# - Kubernetes Probes: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# - Resource Management: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      imagePullSecrets:
        - name: regcred
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: order-service
          image: egitangu/order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          readinessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq.messaging.svc.cluster.local"
            - name: POSTGRES_HOST
              value: "postgres-postgresql.database.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: postgres-database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: postgres-password
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: rabbitmq-password
          volumeMounts:
            - name: logs-and-metrics
              mountPath: /app/logs
      volumes:
        - name: logs-and-metrics
          emptyDir: {}
