apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: egitangu/order-service:latest
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:mysecretpassword@postgres/orders_db
        - name: RABBITMQ_HOST
          value: rabbitmq
