# Kubernetes HorizontalPodAutoscaler manifest for the Order Service
# This HPA automatically scales the order service based on CPU and memory utilization.
#
# Key components:
# - Targets order-service deployment in ecommerce namespace
# - Scales between 1-5 replicas
# - Triggers scaling at:
#   * 50% CPU utilization
#   * 70% memory utilization
#
# References:
# - HPA v2 API: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/
# - HPA Walkthrough: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-service-hpa
  namespace: ecommerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
