# Prometheus Configuration for Microservices Monitoring
# This configuration sets up Prometheus to scrape metrics from the microservices
# and infrastructure components.
#
# Key components:
# - Global settings:
#   * 15s scrape and evaluation intervals
# - Scrape configs:
#   * Flask microservices metrics endpoints
#   * RabbitMQ metrics
#
# References:
# - Prometheus Configuration: https://prometheus.io/docs/prometheus/latest/configuration/configuration/
# - Prometheus Best Practices: https://prometheus.io/docs/practices/naming/
# - Flask Prometheus Metrics: https://github.com/prometheus/client_python

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "flask-services"
    metrics_path: /metrics
    static_configs:
      - targets:
          - catalog-service:5001
          - search-service:5002
          - order-service:5003
          - frontend-service:5004
  - job_name: "rabbitmq"
    metrics_path: /metrics
    static_configs:
      - targets:
          - rabbitmq-service:15672
